config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'ui_kit', to: 'pages#ui_kit'
  get 'admin', to: 'pages#admin'
  resources :cars
  resources :drivers
  resources :circuits
  resources :races, only: [:index]
  resources :teams, only: [ :index, :create, :update ] do
    resources :championships, only: [ :new, :create ]
    member do
      get :join_championship
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :linups
end

app/models/championship.rb
class Championship < ApplicationRecord
  has_many :teams

end

app/models/circuit.rb
class Circuit < ApplicationRecord
  has_many :races
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :car
  has_many :linups
  has_many :race_positions
end

app/models/lineup.rb
class Lineup < ApplicationRecord
  belongs_to :driver
  belongs_to :car
  belongs_to :team
  belongs_to :race
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :circuit
  has_many :race_positions
  has_many :linups
end

app/models/race_position.rb
class RacePosition < ApplicationRecord
  belongs_to :driver
  belongs_to :race
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :championship
  has_many :linups

  COLOR = ['rouge', 'bleu', 'blanc', 'vert', 'orange', 'jaune', 'noir', 'violet']
  LOGO = ['cheval', 'chapeau', 'reine', 'eclair', 'chevrons', 'pomme', 'dragon', 'colombe', 'hyppo', 'kiwi']
  validates :color, presence: true, inclusion: { in: COLOR }
  validates :logo, presence: true, inclusion: { in: LOGO }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :teams

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = policy_scope(Car).sort_by(&:name)
  end

  def new
    @car = Car.new()
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    authorize @car
    if @car.save!
      @car.save
      flash[:notice] = "Voiture créée"
      redirect_to cars_path
    else
      flash[:notice] = "Il y a eu un problème"
      redirect_to new_car_path
    end
  end

  def edit
    @car = Car.find(params[:id])
    authorize @car
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    authorize @car
    redirect_to cars_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    authorize @car
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(
      :name,
      :price
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: [ :home ], :raise => false

  def home
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = policy_scope(Race)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>VroomVroom - Défis tes amis</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/admin.html.erb
<div class="container">
  <h3 class="text-primary mt-2">Admin</h3>
  <div class="row mt-1">
    <%= link_to "les voitures", cars_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    <%= link_to "les pilotes", drivers_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    <%= link_to "les circuits", circuits_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container">

  <h1 class="mt-3">Vroom Vroom</h1>

  <% if user_signed_in? %>
    <h6 class="text-primary mt-2">Vous êtes déjà connecté</h6>
    <div class="row mt-1">
      <%= link_to "mes écuries", teams_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
      <%= link_to "admin", admin_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
      <%= link_to ui_kit_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" do %>
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="green-text">ui kit vroom vroom</span>
        </div>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg btn-block" do %>
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="red-text">déconnexion</span>
        </div>
      <% end %>
    </div>
  <% else %>
    <h6 class="text-primary mt-2">Vous voulez jouer ?</h6>
    <div class="row mt-1">
       <div class="col-2"></div>
       <%= link_to "Créez un compte", new_user_registration_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    </div>
    <div class="row">
       <div class="col-2"></div>
       <%= link_to "Bro, j'ai déjà une écurie...", new_user_session_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    </div>
    <hr style="background-color: white" class="mb-3">
    <div class="vroom-card-body card-body text-center home-explications">
      <h3 class="card-title">Mais c'est quoi, au fait?</h3>
      <h6 class="card-subtitle mb-2 text-muted">↓T'inquiètes bonhomme, je m'en va tout t'expliquer↓</h6>
    <hr style="background-color: white" class="mb-3">

      <div class="vroom-card vroom-border-green card mb-3">
        <div class="row no-gutters">
          <div class="col-4">
            <img src="https://images.unsplash.com/photo-1574785525103-c35dd9b6bb91?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" class="vroom-card-img card-img" alt="Hello">
          </div>
          <div class="col-8">
            <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
              <h4 class="card-title">Tu touches un peu en F1 ?</h4>
              <p class="card-text font-weight-light">VrouVroum te permet de montrer que tu ferais un meilleur Team Principal que tes potes</p>
  <!--                 <p class="card-text"><small class="text-muted">Météo</small></p>
  -->          </div>
          </div>
        </div>
      </div>

      <div class="vroom-card vroom-border-green card mb-3">
        <div class="row no-gutters">
          <div class="col-4">
            <img src="https://images.unsplash.com/photo-1501940740999-480321d51e5a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" class="vroom-card-img card-img" alt="Hello">
          </div>
          <div class="col-8">
            <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
              <h4 class="card-title">Crée un championat avec tes potes</h4>
              <p class="card-text font-weight-light">Nombre de courses ? Nombre de joueurs ? T'es libre, bro. On est pas là pour te juger...</p>
  <!--                 <p class="card-text"><small class="text-muted">Météo</small></p>
  -->          </div>
          </div>
        </div>
      </div>

      <div class="vroom-card vroom-border-green card mb-3">
        <div class="row no-gutters">
          <div class="col-4">
            <img src="https://images.unsplash.com/photo-1579225663317-c0251b4369bc?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" class="vroom-card-img card-img" alt="Hello">
          </div>
          <div class="col-8">
            <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
              <h4 class="card-title">Avant chaque weekend de Grand Prix, fais ton marché</h4>
              <p class="card-text font-weight-light">T'as un budg' pour la saison, et chaque weekend tu flambes comme à Deauville : 2 pilotes & 2 voitures en enchérissant contre tes potes...</p>
  <!--                 <p class="card-text"><small class="text-muted">Météo</small></p>
  -->          </div>
          </div>
        </div>
      </div>

      <div class="vroom-card vroom-border-green card mb-3">
        <div class="row no-gutters">
          <div class="col-4">
            <img src="https://media.speedcafe.com/wp-content/uploads/2020/11/shoey_imola-scaled.jpeg" class="vroom-card-img card-img" alt="Hello">
          </div>
          <div class="col-8">
            <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
              <h4 class="card-title">Après la course, le classement</h4>
              <p class="card-text font-weight-light">Tous les lundis tu découvres si t'es une rock star ou un f***ing wanker !</p>
  <!--                 <p class="card-text"><small class="text-muted">Météo</small></p>
  -->        </div>
          </div>
        </div>
      </div>
      <div class="row mt-1">
        <div class="col-2"></div>
        <%= link_to "Tu m'as convaincu, je crée mon compte", new_user_registration_path, class: "mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
      </div>
    </div>
  <% end %>

</div>

app/views/pages/ui_kit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1501940740999-480321d51e5a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1 class="text-center">Bannière</h1>
  </div>
</div>

<div class="container" style="margin-bottom: 65px">

  <%= link_to "retour à la home", root_path, class: "mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg btn-block" %>

  <!-- BUTTONS -->
  <h3 class="mt-3 text-center"><i class="far fa-hand-pointer"></i> Buttons</h3>
  <hr style="background-color: white" class="mb-3">

  <!-- ---------------- Large Buttons ---------------- -->

  <!-- plain red -->

  <button type="button" class="mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg btn-block">lg btn</button>

  <!-- outlined red -->
  <button type="button" class="mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg btn-block">
    <div class="vroom-inmod btn btn-lg btn-block">
      <span class="red-text">lg btn</span>
    </div>
  </button>

  <!-- plain green -->
  <button type="button" class="mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">lg btn</button>

  <!-- outlined green -->
  <button type="button" class="mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
    <div class="vroom-inmod btn btn-lg btn-block">
      <span class="green-text">lg btn</span>
    </div>
  </button>


  <!-- ---------------- Small Buttons ---------------- -->
  <div class="d-flex justify-content-between">
    <!-- plain red -->
    <button type="button" class="mt-3 vroom-btn-sm vroom-red btn btn-primary btn-lg">sm btn</button>

    <!-- outline red -->
    <button type="button" class="mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg">
      <div class="vroom-inmod-sm btn btn-lg btn-block">
        <span class="mx-2 red-text">sm btn</span>
      </div>
    </button>

    <!-- plain green -->
    <button type="button" class="mt-3 vroom-btn-sm vroom-green btn btn-primary btn-lg">sm btn</button>

    <!-- outlined green -->
    <button type="button" class="mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg">
      <div class="vroom-inmod-sm btn btn-lg btn-block">
        <span class="mx-2 green-text">sm btn</span>
      </div>
    </button>
  </div>

  <!-- ---------------- Round Buttons ---------------- -->
  <div class="d-flex justify-content-around">
    <!-- plain red -->
    <button type="button" class="mt-3 vroom-btn-rd vroom-red btn btn-primary btn-lg"><i class="fas fa-times"></i></button>

    <!-- outline red -->
    <button type="button" class="mt-3 vroom-btn-rd vroom-red btn btn-primary btn-lg">
      <div class="vroom-inmod-sm btn btn-lg btn-block">
        <span class="red-text"><i class="fas fa-times"></i></span>
      </div>
    </button>

    <!-- plain green -->
    <button type="button" class="mt-3 vroom-btn-rd vroom-green btn btn-primary btn-lg"><i class="fas fa-times"></i></button>

    <!-- outlined green -->
    <button type="button" class="mt-3 vroom-btn-rd vroom-green btn btn-primary btn-lg">
      <div class="vroom-inmod-sm btn btn-lg btn-block">
        <span class="green-text"><i class="fas fa-times"></i></span>
      </div>
    </button>
  </div>

  <br>

  <!-- CARDS -->
  <h3 class="mt-3 text-center"><i class="far fa-image"></i> Cards</h3>
  <hr style="background-color: white" class="mb-3">

  <!-- ---------------- Horizontal card ---------------- -->
  <div class="vroom-card vroom-border-green card mb-3">
    <div class="row no-gutters">
      <div class="col-4">
        <img src="https://rivierabarcrawltours.com/wp-content/uploads/2020/03/where-is-monaco-located.-pic-1.jpg" class="vroom-card-img card-img" alt="Hello">
      </div>
      <div class="col-8">
        <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
          <h4 class="card-title">Nom de la course</h4>
          <p class="card-text font-weight-light">Date de la course</p>
          <p class="card-text font-weight-bold">Nombre de tours</p>
          <p class="card-text"><small class="text-muted">Météo</small></p>
        </div>
      </div>
    </div>
  </div>

  <!-- ---------------- Big card ---------------- -->
  <div class="vroom-card vroom-border-red card mb-3">
    <div class="vroom-card-body card-body text-center">
      <h3 class="card-title">Team Name</h3>
      <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <div class="my-1 d-flex justify-content-around">
        <div class="vroom-medal vroom-team-logo"><i class="fas fa-horse"></i></div>
        <div class="vroom-medal vroom-team-info d-flex flex-column justify-content-center"><i class="fas fa-trophy"></i>P4</div>
        <div class="vroom-medal vroom-team-info d-flex flex-column justify-content-center"><i class="fas fa-chart-line"></i>456pts</div>
      </div>
      <div class="mb-1 d-flex justify-content-around">
        <button type="button" class="mx-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
          <div class="vroom-inmod btn btn-lg btn-block">
            <span class="green-text">lg btn</span>
          </div>
        </button>
        <button type="button" class=" mx-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">lg btn</button>
      </div>
    </div>
  </div>

  <!-- MODAL -->
  <h3 class="mt-3 text-center"><i class="fas fa-expand"></i> Modal</h3>
  <hr style="background-color: white" class="mb-3">

  <!-- Button trigger modal -->
  <button type="button" class="mt-3 vroom-btn-lg vroom-red btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">
    ouvrir la modale
  </button>

  <!-- Modal -->
  <div class="modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="vroom-modal modal-content animate-bottom pb-2">
        <div class="mt-1 d-flex justify-content-center">
          <h4 class="modal-title text-center" id="exampleModalLabel">Titre de la modale</h4>
        </div>
        <div class="mb-2 vroom-modal-body modal-body">
          <p>Contenu de la modale</p>
          <p>Contenu de la modale</p>
          <p>Contenu de la modale</p>
          <div class="mb-1 d-flex justify-content-around">
            <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" data-dismiss="modal">
              <div class="vroom-inmod btn btn-lg btn-block">
                <span class="green-text">fermer</span>
              </div>
            </button>
            <button type="button" class="ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">ok</button>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<!-- Nav Bar -->
<div class="px-3 fixed-bottom mt-2 vroom-navbar d-flex justify-content-around bd-highlight">
  <div class="btn btn-lg">Menu 1</div>
  <div class="vroom-divider my-2"></div>
  <div class="btn btn-lg active">Menu 2</div>
  <div class="vroom-divider my-2"></div>
  <div class="btn btn-lg">Menu 3</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_newchampionship.html.erb
<%= simple_form_for [@team, @championship] do |f| %>
            <%= f.input :name,
                        label: "Nom du championat",
                        placeholder: "Donnez un nom au championat" %>
            <%= f.input :participants_number,
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item',
                        collection: (2..10),
                        label: "Nombre max de participants" %>
            <%= f.input :race_number,
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item',
                        collection: [3, 5, 10, 20, 23],
                        label: "Nombre de grand-prix" %>
  <div>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
    <%= link_to teams_path do %>
      <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="green-text">en fait non</span>
        </div>
      </button>
    <% end %>
  </div>
<% end %>

app/views/shared/_newteam.html.erb
<%= simple_form_for @team do |f| %>
            <%= f.input :name,
                        label: "Nom d'écurie",
                        placeholder: "Donnez un nom à votre écurie" %>
            <%= f.input :logo,
                        label: "Blaz de l'écurie",
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item',
                        collection: Team::LOGO %>
            <%= f.input :color,
                        label: "Couleur de l'écurie",
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item',
                        collection: Team::COLOR %>
  <div class="mb-1 d-flex justify-content-around">
      <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" data-dismiss="modal">
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="green-text">en fait non</span>
        </div>
      </button>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>