config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'ui_kit', to: 'pages#ui_kit'
  get 'admin', to: 'pages#admin'
  resources :cars
  resources :drivers
  resources :circuits
  resources :races, only: [:index]
  resources :teams, only: [ :index, :create, :update ] do
    resources :championships, only: [ :new, :create ]
    member do
      get :join_championship
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :linups
end

app/models/championship.rb
class Championship < ApplicationRecord
  has_many :teams

end

app/models/circuit.rb
class Circuit < ApplicationRecord
  has_many :races
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :car
  has_many :linups
  has_many :race_positions
end

app/models/lineup.rb
class Lineup < ApplicationRecord
  belongs_to :driver
  belongs_to :car
  belongs_to :team
  belongs_to :race
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :circuit
  has_many :race_positions
  has_many :linups
end

app/models/race_position.rb
class RacePosition < ApplicationRecord
  belongs_to :driver
  belongs_to :race
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :championship
  has_many :linups

  COLOR = ['rouge', 'bleu', 'blanc', 'vert', 'orange', 'jaune', 'noir', 'violet']
  LOGO = ['cheval', 'chapeau', 'reine', 'eclair', 'chevrons', 'pomme', 'dragon', 'colombe', 'hyppo', 'kiwi']
  validates :color, presence: true, inclusion: { in: COLOR }
  validates :logo, presence: true, inclusion: { in: LOGO }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :teams

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = policy_scope(Car).sort_by(&:name)
  end

  def new
    @car = Car.new()
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    authorize @car
    if @car.save!
      @car.save
      flash[:notice] = "Voiture créée"
      redirect_to cars_path
    else
      flash[:notice] = "Il y a eu un problème"
      redirect_to new_car_path
    end
  end

  def edit
    @car = Car.find(params[:id])
    authorize @car
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    authorize @car
    redirect_to cars_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    authorize @car
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(
      :name,
      :price
    )
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = policy_scope(Driver).sort_by(&:name)
  end

  def new
    @driver = Driver.new()
    authorize @driver
  end

  def create
    @driver = Driver.new(driver_params)
    authorize @driver
    if @driver.save!
      @driver.save
      flash[:notice] = "Pilote créé"
      redirect_to drivers_path
    else
      flash[:notice] = "Il y a eu un problème"
      redirect_to new_driver_path
    end
  end

  def edit
    @driver = Driver.find(params[:id])
    authorize @driver
  end

  def update
    @driver = Driver.find(params[:id])
    @driver.update(driver_params)
    authorize @driver
    redirect_to drivers_path
  end

  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy
    authorize @driver
    redirect_to drivers_path
  end

  private

  def driver_params
    params.require(:driver).permit(
      :name,
      :price
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: [ :home ], :raise => false

  def home
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = policy_scope(Race)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = policy_scope(Team)
    @team = Team.new()
    @logos = logos
    # raise
  end

  def create
    @team = current_user.teams.new(team_params)
    @team.budget = 200_000
    @team.points = 0
    @team.championship = Championship.first
    authorize @team
    if @team.save!
      flash[:notice] = "Ecurie crée"
      redirect_to teams_path
    else
      flash[:notice] = "Il y a eu un problème"
      redirect_to teams_path
    end
  end

  def join_championship
    @team = Team.find(params[:id])
    authorize @team
  end

  def update
    @team = Team.find(params[:id])
    authorize @team
    @team.sharing_code = team_params[:sharing_code]
    @team.championship = Championship.find_by(sharing_code: @team.sharing_code)
    if @team.save!
      flash[:notice] = "Ecurie mise à jour"
      redirect_to teams_path
    else
      flash[:notice] = "Il y a eu un problème"
      redirect_to teams_path
    end
  end

  private

  def team_params
    params.require(:team).permit(
      :name,
      :logo,
      :sharing_code,
      :color
    )
  end

  def logos
    {
      cheval: 'fas fa-horse',
      chapeau: 'fas fa-hat-cowboy',
      reine: 'fas fa-chess-queen',
      eclair: 'fas fa-bolt',
      chevrons: 'fas fa-angle-double-down',
      pomme: 'fas fa-apple-alt',
      dragon: 'fas fa-dragon',
      colombe: 'fas fa-dove',
      hyppo: 'fas fa-hippo',
      kiwi: 'fas fa-kiwi-bird'

    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/cars/edit.html.erb
<div class="container">
  <h1 class="mt-3">Éditer les infos</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :name,
                label: "Nom de la voiture" %>
    <%= f.input :price,
                label: "Prix de la voiture par course (€)"%>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
  <% end %>
  <%= link_to cars_path do %>
    <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
      <div class="vroom-inmod btn btn-lg btn-block">
        <span class="green-text">en fait non</span>
      </div>
    </button>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="container">
  <h1 class="mt-3">Les voitures</h1>
  <% if @cars.length > 0 %>
    <% @cars.each do |car| %>
      <div class="vroom-card vroom-border-green card mb-3 p-2">
        <div class="row no-gutters">
          <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
            <p class="card-text font-weight-bold"><%= car.name %></p>
            <p class="card-text font-weight-light"><%= car.price %>€/course</p>
          </div>
        </div>
        <div class="d-flex justify-content-around mt-1">
          <%= link_to edit_car_path(car) do %>
            <button type="button" class="vroom-btn-lg vroom-green btn btn-primary btn-lg">
              <div class="vroom-inmod-sm btn btn-lg btn-block">
                <span class="mx-2 green-text">éditer les infos</span>
              </div>
            </button>
          <% end %>
          <%= link_to car_path(car), method: :delete, data: { confirm: "sûr sûr?" } do %>
            <button type="button" class="vroom-btn-lg vroom-green btn btn-primary btn-lg">
              <div class="vroom-inmod-sm btn btn-lg btn-block">
                <span class="mx-2 green-text">supprimer</span>
              </div>
            </button>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>Aucune voiture n'a été ajoutée !</h3>
  <% end %>
  <%= link_to "ajouter une voiture", new_car_path, class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1 class="mt-3">Ajouter une voiture</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :name,
                label: "Nom de la voiture",
                placeholder: "Tapez le nom de la voiture" %>
    <%= f.input :price,
                label: "Prix de la voiture par course (€)",
                placeholder: "Tapez le prix de la voiture"%>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
  <% end %>
  <%= link_to cars_path do %>
      <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="green-text">en fait non</span>
        </div>
      </button>
    <% end %>
</div>

app/views/drivers/edit.html.erb
<div class="container">
  <h1 class="mt-3">Éditer les infos</h1>
  <%= simple_form_for @driver do |f| %>
    <%= f.input :name,
                label: "Nom du pilote" %>
    <%= f.input :price,
                label: "Prix du pilote par course (€)"%>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
  <% end %>
  <%= link_to drivers_path do %>
    <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
      <div class="vroom-inmod btn btn-lg btn-block">
        <span class="green-text">en fait non</span>
      </div>
    </button>
  <% end %>
</div>

app/views/drivers/index.html.erb
<div class="container">
  <h1 class="mt-3">Les pilotes</h1>
  <% if @drivers.length > 0 %>
    <% @drivers.each do |driver| %>
      <div class="vroom-card vroom-border-green card mb-3 p-2">
        <div class="row no-gutters">
          <div class="vroom-card-body card-body h-100 d-flex flex-column justify-content-between">
            <p class="card-text font-weight-bold"><%= driver.name %></p>
            <p class="card-text font-weight-light"><%= driver.price %>€/course</p>
          </div>
        </div>
        <div class="d-flex justify-content-around mt-1">
          <%= link_to edit_car_path(driver) do %>
            <button type="button" class="vroom-btn-lg vroom-green btn btn-primary btn-lg">
              <div class="vroom-inmod-sm btn btn-lg btn-block">
                <span class="mx-2 green-text">éditer les infos</span>
              </div>
            </button>
          <% end %>
          <%= link_to car_path(driver), method: :delete, data: { confirm: "sûr sûr?" } do %>
            <button type="button" class="vroom-btn-lg vroom-green btn btn-primary btn-lg">
              <div class="vroom-inmod-sm btn btn-lg btn-block">
                <span class="mx-2 green-text">supprimer</span>
              </div>
            </button>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>Aucun pilote n'a été ajouté !</h3>
  <% end %>
  <%= link_to "ajouter un pilote", new_driver_path, class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
</div>

app/views/drivers/new.html.erb
<div class="container">
  <h1 class="mt-3">Ajouter une voiture</h1>
  <%= simple_form_for @driver do |f| %>
    <%= f.input :name,
                label: "Nom du pilote",
                placeholder: "Tapez le nom du pilote" %>
    <%= f.input :price,
                label: "Prix du pilote par course (€)",
                placeholder: "Tapez le prix du pilote"%>
    <%= f.submit "c'est parti", class: "ml-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block" %>
  <% end %>
  <%= link_to drivers_path do %>
      <button type="button" class="mr-1 mt-3 vroom-btn-lg vroom-green btn btn-primary btn-lg btn-block">
        <div class="vroom-inmod btn btn-lg btn-block">
          <span class="green-text">en fait non</span>
        </div>
      </button>
    <% end %>
</div>

app/views/races/index.html.erb
<% if @races.length > 0 %>
  <% @races.each do |race| %>
    <%= race.circuit_id.name %>
  <% end %>
<% else %>
  <h3>No races entered yet !</h3>
<% end %>

<%= link_to "add a race", new_race_path %>